export {
  IconHome,
  IconCategory,
  IconLayoutColumns,
  IconAdjustments,
  IconUser,
  IconPlayerPlay,
  IconPlayerPause,
  IconPlayerSkipForward,
  IconPlayerSkipBack,
  IconChevronUp,
  IconChevronDown,
  IconDots,
  IconCopy,
  IconLogout,
  IconLoader,
  IconAlertTriangle,
  IconArrowLeft,
  IconDotsVertical,
  IconTrash,
} from '@tabler/icons-react';
