name: clouder_analytics
version: "1.0.0"
config-version: 2
profile: clouder_analytics

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

vars:
  lookback_days: 3

models:
  clouder_analytics:
    +materialized: view
    silver:
      +materialized: incremental
      +incremental_strategy: insert_overwrite
      +table_type: hive
      +partitioned_by: ["dt"]
    gold:
      dims:
        +materialized: table
      facts:
        +materialized: incremental
        +incremental_strategy: insert_overwrite
        +table_type: hive
        +partitioned_by: ["dt"]
